
DATABASE_USER = 'postgres'
DATABASE_PASSWORD = 'G69e5Lxeiu'
DATABASE_HOST = '192.168.100.40'
DATABASE_PORT = '5432'
DATABASE_NAME = 'postgres'
DATABASE_URL = f"postgresql+asyncpg://{DATABASE_USER}:{DATABASE_PASSWORD}" \
         f"@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
